export const MOTIVATIONAL_QUOTES = [
    "La única forma de hacer un gran trabajo es amar lo que haces. - Steve Jobs",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. - Albert Schweitzer",
    "No esperes. El tiempo nunca será el justo. - Napoleon Hill",
    "Todo lo que puedas imaginar es real. - Pablo Picasso",
    "La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello. - Charles R. Swindoll",
    "Cree que puedes y ya estarás a medio camino. - Theodore Roosevelt",
    "El único límite para nuestra comprensión del mañana serán nuestras dudas del presente. - Franklin D. Roosevelt",
    "Actúa como si lo que haces marcara la diferencia. Lo hace. - William James",
    "El éxito suele llegar a quienes están demasiado ocupados para buscarlo. - Henry David Thoreau",
    "No cuentes los días, haz que los días cuenten. - Muhammad Ali",
    "El futuro pertenece a quienes creen en la belleza de sus sueños. - Eleanor Roosevelt",
    "La mejor manera de predecir el futuro es crearlo. - Peter Drucker",
    "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de alguien más. - Steve Jobs",
    "No he fallado. Solo he encontrado 10.000 maneras que no funcionan. - Thomas A. Edison",
    "La lógica te llevará de A a B. La imaginación te llevará a cualquier parte. - Albert Einstein",
    "El éxito es ir de fracaso en fracaso sin perder el entusiasmo. - Winston Churchill",
    "Siempre parece imposible hasta que se hace. - Nelson Mandela",
    "No busques el éxito si lo deseas; haz lo que amas y crees, y el éxito vendrá naturalmente. - David Frost",
    "La mejor venganza es el éxito masivo. - Frank Sinatra",
    "Si puedes soñarlo, puedes hacerlo. - Walt Disney",
    "El hombre que mueve una montaña comienza cargando pequeñas piedras. - Confucio",
    "La disciplina es el puente entre metas y logros. - Jim Rohn",
    "No te detengas cuando estés cansado. Detente cuando hayas terminado. - Marilyn Monroe",
    "La perseverancia es fallar 19 veces y tener éxito la vigésima. - Julie Andrews",
    "El secreto de avanzar es comenzar. - Mark Twain",
    "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud. - Maya Angelou",
    "El fracaso es el condimento que da sabor al éxito. - Truman Capote",
    "La creatividad es la inteligencia divirtiéndose. - Albert Einstein",
    "Nunca es demasiado tarde para ser lo que podrías haber sido. - George Eliot",
    "Todo logro comienza con la decisión de intentarlo. - Gail Devers",
    "No dejes que el ayer ocupe demasiado del hoy. - Will Rogers",
    "Aprendes más del fracaso que del éxito. No dejes que te detenga. El fracaso construye carácter. - Desconocido",
    "Si estás trabajando en algo que te importa de verdad, nadie tiene que empujarte: tu visión te empuja. - Steve Jobs",
    "La gente suele decir que la motivación no dura. Bueno, tampoco lo hace el baño. Por eso se recomienda a diario. - Zig Ziglar",
    "Intenta no volverte un hombre de éxito, sino volverte un hombre de valor. - Albert Einstein",
    "No es la carga lo que te rompe, sino la forma en que la llevas. - Lou Holtz",
    "Lo único imposible es aquello que no intentas. - Desconocido",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
    "La excelencia no es un acto, sino un hábito. - Aristóteles",
    "Haz lo que puedas, con lo que tengas, donde estés. - Theodore Roosevelt",
    "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad. - Séneca",
    "No midas tu riqueza por el dinero que tienes, mídela por aquellas cosas que tienes y que no cambiarías por dinero. - Paulo Coelho",
    "La verdadera oportunidad hacia el éxito yace en la persona y no en el puesto de trabajo. - Zig Ziglar",
    "Cáete siete veces y levántate ocho. - Proverbio japonés",
    "El conocimiento habla, pero la sabiduría escucha. - Jimi Hendrix",
    "La vida no se trata de encontrarte a ti mismo. La vida se trata de crearte a ti mismo. - George Bernard Shaw",
    "No importa lo lento que vayas, siempre y cuando no te detengas. - Confucio",
    "La calidad no es un acto, es un hábito. - Aristóteles",
    "Prefiero morir de pasión que de aburrimiento. - Vincent van Gogh",
    "El poder de la imaginación nos hace infinitos. - John Muir",
    "Solo aquellos que se atreven a fallar grandemente pueden lograr grandezas. - Robert F. Kennedy",
    "La innovación distingue a los líderes de los seguidores. - Steve Jobs",
    "Si quieres vivir una vida feliz, átala a una meta, no a personas o cosas. - Albert Einstein",
    "Nuestra mayor gloria no está en no caer nunca, sino en levantarnos cada vez que caemos. - Confucio",
    "El pesimista ve dificultad en toda oportunidad. El optimista ve oportunidad en toda dificultad. - Winston Churchill",
    "Tener éxito no es aleatorio. Es trabajo duro, perseverancia, aprendizaje, estudio, sacrificio y, sobre todo, amor por lo que estás haciendo o aprendiendo a hacer. - Pelé",
    "La simplicidad es la máxima sofisticación. - Leonardo da Vinci",
    "No puedes cruzar el mar simplemente mirando el agua. - Rabindranath Tagore",
    "Mantén tu rostro siempre hacia la luz del sol y las sombras caerán detrás de ti. - Walt Whitman",
    "Sé el cambio que quieres ver en el mundo. - Mahatma Gandhi",
    "Lo que conseguimos con mucha facilidad, lo estimamos en poco. - Thomas Paine",
    "La felicidad no es algo hecho. Proviene de tus propias acciones. - Dalai Lama",
    "Es durante nuestros momentos más oscuros cuando debemos centrarnos para ver la luz. - Aristóteles Onassis",
    "Cree en ti mismo y en todo lo que eres. Reconoce que hay algo dentro de ti que es más grande que cualquier obstáculo. - Christian D. Larson",
    "El único lugar donde el éxito viene antes que el trabajo es en el diccionario. - Vidal Sassoon",
    "No tengas miedo de renunciar a lo bueno para ir a por lo grandioso. - John D. Rockefeller",
    "Empieza donde estás. Usa lo que tienes. Haz lo que puedas. - Arthur Ashe",
    "Si la oportunidad no llama, construye una puerta. - Milton Berle",
    "El éxito es caer nueve veces y levantarse diez. - Jon Bon Jovi",
    "No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas. - Robert Louis Stevenson",
    "La mejor preparación para mañana es hacer lo mejor que puedas hoy. - H. Jackson Brown, Jr.",
    "El momento es ahora. - Anónimo",
    "No dejes que el ruido de las opiniones ajenas apague tu voz interior. - Steve Jobs",
    "La vida es un 10% lo que me ocurre y un 90% cómo reacciono a ello. - John Maxwell",
    "Solo se vive una vez, pero si lo haces bien, una vez es suficiente. - Mae West",
    "El secreto de la felicidad no es hacer siempre lo que se quiere, sino querer siempre lo que se hace. - León Tolstói",
    "El coraje no siempre ruge. A veces el coraje es la pequeña voz al final del día que dice: lo intentaré de nuevo mañana. - Mary Anne Radmacher",
    "La vida es lo que pasa mientras estás ocupado haciendo otros planes. - John Lennon",
    "El fracaso no es lo opuesto al éxito, es parte del éxito. - Arianna Huffington",
    "Cree en ti mismo y serás imparable. - Anónimo",
    "Hazlo con pasión o no lo hagas. - Rosa Nouchette Carey",
    "La educación es el arma más poderosa que puedes usar para cambiar el mundo. - Nelson Mandela",
    "No importa lo que te diga la gente, las palabras y las ideas pueden cambiar el mundo. - Robin Williams",
    "Si no puedes volar, corre; si no puedes correr, camina; si no puedes caminar, gatea, pero sigue avanzando. - Martin Luther King Jr.",
    "La duda mata más sueños que el fracaso. - Suzy Kassem",
    "No hay atajos para cualquier lugar al que valga la pena ir. - Beverly Sills",
    "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene. - Henry Ford",
    "No permitas que el miedo a perder sea mayor que la emoción de ganar. - Robert Kiyosaki",
    "Tu actitud, no tu aptitud, determinará tu altitud. - Zig Ziglar",
    "Si quieres algo que nunca has tenido, tendrás que hacer algo que nunca has hecho. - Thomas Jefferson",
    "La mejor salida es siempre a través. - Robert Frost",
    "El optimismo es la fe que conduce al logro. Nada puede hacerse sin esperanza y confianza. - Helen Keller",
    "El genio es 1% de talento y 99% de trabajo duro. - Albert Einstein",
    "Las dificultades preparan a personas comunes para destinos extraordinarios. - C.S. Lewis",
    "No sueñes tu vida, vive tu sueño. - Anónimo",
    "La vida es una aventura atrevida o no es nada. - Helen Keller",
    "Cada día es una nueva oportunidad para cambiar tu vida. - Anónimo",
    "Si el plan no funciona, cambia el plan, pero no cambies la meta. - Anónimo",
    "El éxito no se mide por lo que logras, sino por los obstáculos que superas. - Booker T. Washington",
    "La única manera de hacer un gran trabajo es amar lo que haces. - Steve Jobs",
    "No te compares con nadie en este mundo. Si lo haces, te estás insultando a ti mismo. - Bill Gates",
    "La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas. - Jim Ryun",
    "No mires el reloj; haz lo que él hace. Sigue adelante. - Sam Levenson",
    "Todo parece imposible hasta que se hace. - Nelson Mandela",
    "El éxito es la capacidad de ir de fracaso en fracaso sin perder el entusiasmo. - Winston Churchill",
    "Cree que puedes y ya estás a medio camino. - Theodore Roosevelt",
    "La felicidad no es algo que pospones para el futuro; es algo que diseñas para el presente. - Jim Rohn",
    "No cuentes los días, haz que los días cuenten. - Muhammad Ali",
    "El único lugar donde el éxito viene antes que el trabajo es en el diccionario. - Vidal Sassoon",
    "No dejes que lo que no puedes hacer interfiera con lo que puedes hacer. - John Wooden",
    "La mejor manera de predecir el futuro es crearlo. - Peter Drucker",
    "No tengas miedo de renunciar a lo bueno para ir a por lo grandioso. - John D. Rockefeller",
    "El fracaso es solo la oportunidad de comenzar de nuevo de forma más inteligente. - Henry Ford",
    "La vida es corta. Sonríele a quien llora, ignora a quien te critica y sé feliz con quien te importa. - Anónimo",
    "Haz hoy lo que otros no quieren, haz mañana lo que otros no pueden. - Jerry Rice",
    "Si no luchas por lo que quieres, no te lamentes por lo que pierdes. - Anónimo",
    "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje para continuar. - Winston Churchill",
    "La única discapacidad en la vida es una mala actitud. - Scott Hamilton",
    "Si crees que puedes, tienes razón. Si crees que no puedes, también tienes razón. - Henry Ford",
    "La verdadera medida de la grandeza no es cuánto tiempo vives, sino cuánto amor das. - Madre Teresa",
    "No esperes oportunidades extraordinarias. Aprovecha ocasiones comunes y hazlas grandes. - Orison Swett Marden",
    "La vida no se mide por las veces que respiras, sino por los momentos que te dejan sin aliento. - Hitch",
    "Si quieres ir rápido, ve solo. Si quieres ir lejos, ve acompañado. - Proverbio africano",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
    "Lo que haces hoy puede mejorar todos tus mañanas. - Ralph Marston",
    "No dejes que el miedo a fallar te impida jugar. - Babe Ruth",
    "La única limitación es la que pones en tu propia mente. - Napoleon Hill",
    "El éxito llega cuando tus sueños son más grandes que tus excusas. - Anónimo",
    "No busques culpables, busca soluciones. - Henry Ford",
    "La vida es un eco. Si no te gusta lo que recibes, fíjate en lo que emites. - Anónimo",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. - Albert Schweitzer",
    "Si no te gusta dónde estás, muévete. No eres un árbol. - Jim Rohn",
    "La perseverancia es el trabajo duro que haces después de cansarte del trabajo duro que ya hiciste. - Newt Gingrich",
    "No importa cuántas veces te equivoques o con qué lentitud progreses, sigues estando muy por delante de los que ni siquiera lo intentan. - Tony Robbins",
    "Las mejores cosas de la vida no son cosas. - Art Buchwald",
    "El riesgo más grande es no tomar ninguno. - Mark Zuckerberg",
    "Si puedes soñarlo, puedes hacerlo. - Walt Disney",
    "La vida es muy simple, pero insistimos en hacerla complicada. - Confucio",
    "No ganes el mundo y pierdas tu alma; la sabiduría es mejor que la plata o el oro. - Bob Marley",
    "El éxito es gustarte a ti mismo, gustarte lo que haces y gustarte cómo lo haces. - Maya Angelou",
    "La mejor forma de predecir tu futuro es construirlo. - Alan Kay",
    "El único modo de hacer un gran trabajo es amar lo que haces. - Steve Jobs",
    "La vida te pondrá obstáculos, pero los límites los pones tú. - Anónimo",
    "No dejes que el éxito se te suba a la cabeza ni que el fracaso se te baje al corazón. - Will Smith",
    "La disciplina es hacer lo que hay que hacer, cuando hay que hacerlo, tengas ganas o no. - Anónimo",
    "El verdadero fracaso no es caer, sino negarse a levantarse. - Proverbio chino"
];
